// Imports
	// Importing components
	import { useEffect } from 'react';
	import LetterGrid from '../../components/LetterGrid.jsx';

	// Importing defs
	import { randomlyChoose } from '../../defs.js';



export default function Temp() {
	return (
		<div className='Temp'>
			{/* The letters should read: FINALFOLIO&RESEARCHJOURNALGEORDIEMARSH */}
			{/* <div className='letters-cont cover-page'>
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="&" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="&" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="&" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="&" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="&" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="&" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="&" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="&" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
			</div> */}
			{/* The letters should read: RESEARCHJOURNALGEORDIEMARSHWIST2024SEM2 */}
			{/* <div className='letters-cont cover-page'>
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="J" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
			</div> */}
			{/* The letters should read: FINALFOLIOGEORDIEMARSH */}
			<div className='letters-cont cover-page'>
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="G" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="H" />
			</div>
			{/* <div className='letters-cont brief1'>
				<LetterGrid mode='set' initialLetter="B" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="I" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="F" />
				<LetterGrid mode='set' initialLetter="4" />
			</div> */}
			{/* <div className='letters-cont name'>
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="S" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="N" />
				<LetterGrid mode='set' initialLetter="C" />
				<LetterGrid mode='set' initialLetter="E" />
			</div>
			<div className='letters-cont name'>
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="D" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="O" />
				<LetterGrid mode='set' initialLetter="R" />
				<LetterGrid mode='set' initialLetter="P" />
				<LetterGrid mode='set' initialLetter="H" />
			</div>
			<div className='letters-cont name'>
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="P" />
				<LetterGrid mode='set' initialLetter="H" />
				<LetterGrid mode='set' initialLetter="E" />
				<LetterGrid mode='set' initialLetter="M" />
				<LetterGrid mode='set' initialLetter="U" />
				<LetterGrid mode='set' initialLetter="L" />
				<LetterGrid mode='set' initialLetter="A" />
				<LetterGrid mode='set' initialLetter="R" />
			</div> */}
		</div>
	);
}